CREATE TABLE CATEGORIES (
	CATEGORY_ID NUMBER PRIMARY KEY,
	CATEGORY_NAME VARCHAR2(100) UNIQUE
);

INSERT INTO CATEGORIES VALUES(
	1, '스마트폰'
);

INSERT INTO CATEGORIES VALUES(
	2, 'TV'
);

INSERT INTO CATEGORIES VALUES(
	3, 'Gaming'
);

CREATE TABLE PRODUCTS (
	PRODUCT_ID NUMBER PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(100) NOT NULL,
	CATEGORY NUMBER,
	PRICE NUMBER DEFAULT 0,
	STOCK_QUANTITY NUMBER DEFAULT 0
);

INSERT INTO PRODUCTS VALUES(
	101, 'Apple iPhone 12', 1, 1500000, 30
);

INSERT INTO PRODUCTS VALUES(
	102, 'Samsung Galaxy S24', 1, 1800000, 50
);

INSERT INTO PRODUCTS VALUES(
	201, 'LG OLED TV', 2, 3600000, 10
);

INSERT INTO PRODUCTS VALUES(
	301, 'Sony PlayStation 5', 3, 700000, 15
);

CREATE TABLE CATEGORIES_FK (
	CATEGORY_ID NUMBER
	CONSTRAINT CATEGORIES_FK REFERENCES CATEGORIES
);

CREATE TABLE CUSTOMERS (
	CUSTOMER_ID NUMBER PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL,
	GENDER CHAR(3) CHECK(GENDER IN('남', '여')),
	ADDRESS VARCHAR2(100),
	PHONE VARCHAR2(30)
);

INSERT INTO CUSTOMERS VALUES(
	1, '홍길동', '남', '서울시 성동구 왕십리', '010-1111-2222'
);

INSERT INTO CUSTOMERS VALUES(
	2, '유관순', '여', '서울시 종로구 안국동', '010-3333-1111'
);

CREATE TABLE ORDERS (
	ORDER_ID NUMBER PRIMARY KEY,
	ORDER_DATE DATE DEFAULT SYSDATE,
	STATUS CHAR(1) CHECK(STATUS IN('Y', 'N') DEFAULT 'N'),
	CUSTOMER_ID NUMBER,
	PHONE VARCHAR2(30)
);

INSERT INTO ORDERS VALUES(
	576, '2024-02-29', '여', '서울시 종로구 안국동', '010-3333-1111'
);

INSERT INTO ORDERS VALUES(
	978, '2024-02-29', '여', '서울시 종로구 안국동', '010-3333-1111'
);

INSERT INTO ORDERS VALUES(
	777, '2024-02-29', '여', '서울시 종로구 안국동', '010-3333-1111'
);

INSERT INTO ORDERS VALUES(
	134, '2024-02-29', '여', '서울시 종로구 안국동', '010-3333-1111'
);

INSERT INTO ORDERS VALUES(
	499, '2024-02-29', '여', '서울시 종로구 안국동', '010-3333-1111'
);

CREATE TABLE ORDERS_FK (
	CUSTOMER_ID NUMBER
	CONSTRAINT ORDERS_PK REFERENCES CUSTOMERS ON DELETE CASCADE
);

CREATE TABLE ORDER_DETAILS (
	ORDER_DETAIL_ID NUMBER PRIMARY KEY,
	ORDER_NUMBER NUMBER,
	PRODUCT_NUMBER NUMBER,
	QUANTITY NUMBER,
	PRICE_PER_UNIT NUMBER
);

CREATE TABLE ORDER_DETAILS_FK1 (
	ORDER_ID NUMBER
	CONSTRAINT ORDER_DETAILS_FK1 REFERENCES ORDERS ON DELETE CASCADE
);

CREATE TABLE ORDER_DETAILS_FK2 (
	PRODUCT_ID NUMBER
	CONSTRAINT ORDERS_PK REFERENCES PRODUCT_ID ON DELETE CASCADE
);
